version: '3'
tasks:
  default:
    cmds:
      - task: lint
      - task: test

  test:
    cmd: go test ./...

  lint:
    cmds:
      - staticcheck ./...

  generate:go:
    cmds:
      - go generate ./...
      - buf generate
      - go mod tidy

  emulators:start:
    cmd: firebase emulators:start --project demo